gg.toast('Loading a values...')
local Brocast ='https://discordapp.com/api/webhooks/480169618720292894/LlwShDo4ipDRO2OvAX2q5gDxjx03sux7p3qmtF09VoyAxGPIAMnWYcezLNFeTrdsg5uv'
local timelim=
 'https://raw.githubusercontent.com/samsamlausam/Script/master/TL.Lua'
local ScriptStats=
 'https://raw.githubusercontent.com/samsamlausam/Script/master/SS.Lua'
local codeing=
'https://raw.githubusercontent.com/samsamlausam/Script/master/AuthOnly.Lua'
local thephonetime=os.date'%Y%m%d%H%M'
local thetimelimit=gg.makeRequest(timelim).contect
local gtrychance = 3
local VaildKeyA = math.random(1000, 9999)
local gappsnow = gg.getTargetInfo()
local gusername1= '@DESPAC1T0#6969'
local gusername2= '@peter00f#9823'
local gacclist = {gusername1,gusername2}
local powersave = 350

