gg.toast('Loading a values...')
local Brocast ='https://discordapp.com/api/webhooks/480169618720292894/LlwShDo4ipDRO2OvAX2q5gDxjx03sux7p3qmtF09VoyAxGPIAMnWYcezLNFeTrdsg5uv'
local timelim=
 'https://raw.githubusercontent.com/samsamlausam/Script/master/TL.Lua'
local ScriptStats=
 'https://raw.githubusercontent.com/samsamlausam/Script/master/SS.Lua'
local codeing=
'https://raw.githubusercontent.com/samsamlausam/Script/master/AuthOnly.Lua'
thephonetime=os.date'%Y%m%d%H%M'
thetimelimit=gg.makeRequest(timelim).contect
LoginWord=''
CYATL="Choose your account to Login"
AuthContiue=0
gappsnow = gg.getTargetInfo()
gusername1= '@DESPAC1T0#6969'
gusername2= '@peter00f#9823'
gacclist = {gusername1,gusername2}
gtrychance = 1
local Brocast ='https://discordapp.com/api/webhooks/480169618720292894/LlwShDo4ipDRO2OvAX2q5gDxjx03sux7p3qmtF09VoyAxGPIAMnWYcezLNFeTrdsg5uv'
authpwdA='19847o9394'
authpwdB='hsi289a;/@ie'
IsLogin='No'

